/**
 * Operational brief — the write-back that closes the loop.
 *
 * Doctrine (Tier 1): insight without execution is an open loop. The brief is
 * GEV's first ACTIONABLE artifact: current picture + anomalies + (optionally)
 * a scenario delta, rendered to Markdown a surface can copy, download, or
 * attach to a share link — from the same surface where the picture lives.
 *
 * Pure: consumes store + alerts (+ scenario comparison), returns data and
 * text. No DOM, no fetch.
 *
 * @module brief/product
 */

function fmtKm(km) {
  if (!Number.isFinite(km)) return '—';
  return `${Math.round(km * 10) / 10} km`;
}

function fmtLatLon(lat, lon) {
  if (!Number.isFinite(lat) || !Number.isFinite(lon)) return 'position unknown';
  return `${Math.abs(lat).toFixed(2)}°${lat >= 0 ? 'N' : 'S'}, ${Math.abs(lon).toFixed(2)}°${lon >= 0 ? 'E' : 'W'}`;
}

/**
 * Compose the brief.
 * @param {object} args
 * @param {object} args.store Ontology store (or scenario branch store).
 * @param {object[]} [args.alerts] Output of evaluateRules.
 * @param {object} [args.scenario] Optional {name, comparison} from the
 *   scenario engine — included as a "What-if delta" section.
 * @param {string} [args.title]
 * @param {() => number} [args.now]
 */
export function composeBrief({ store, alerts = [], scenario = null, title = 'Operational Brief', now = Date.now } = {}) {
  if (!store) return null;
  const counts = store.countsByType();
  const picture = Object.entries(counts)
    .sort((a, b) => a[0].localeCompare(b[0]))
    .map(([type, count]) => ({ type, count }));
  return {
    title,
    generatedAt: new Date(now()).toISOString(),
    picture,
    totals: { objects: store.allObjects().length, alerts: alerts.length },
    alerts,
    scenario,
  };
}

/** Render a composed brief to Markdown — the copy/download/share artifact. */
export function renderBriefMarkdown(brief) {
  if (!brief) return '';
  const lines = [`# ${brief.title}`, '', `Generated: ${brief.generatedAt}`, ''];
  lines.push('## Current picture', '');
  if (brief.picture.length === 0) lines.push('- No objects in the picture.');
  for (const { type, count } of brief.picture) lines.push(`- ${type}: ${count}`);
  lines.push('', `## Alerts (${brief.alerts.length})`, '');
  if (brief.alerts.length === 0) lines.push('- None.');
  for (const a of brief.alerts) {
    const evidence = a.evidence?.corridor
      ? `corridor ${a.evidence.corridor}${a.evidence.distanceKm !== undefined ? ` @ ${fmtKm(a.evidence.distanceKm)}` : ''}`
      : a.evidence?.relatedTo
        ? `${a.evidence.kind} ${a.evidence.relatedTo} @ ${fmtKm(a.evidence.distanceKm)}`
        : a.evidence?.gapMs !== undefined
          ? `dark for ${Math.round(a.evidence.gapMs / 60000)} min`
          : '—';
    lines.push(`- **[${a.severity.toUpperCase()}]** ${a.label} (${a.objectType}) — ${a.ruleId}; ${evidence}; ${fmtLatLon(a.lat, a.lon)}`);
  }
  if (brief.scenario?.comparison) {
    const c = brief.scenario.comparison;
    lines.push('', `## What-if: ${brief.scenario.name}`, '');
    lines.push(`- New alerts under scenario: ${c.addedAlerts.length}`);
    for (const a of c.addedAlerts) lines.push(`  - [${a.severity.toUpperCase()}] ${a.label} — ${a.ruleId}`);
    lines.push(`- Alerts resolved under scenario: ${c.removedAlerts.length}`);
    for (const a of c.removedAlerts) lines.push(`  - [${a.severity.toUpperCase()}] ${a.label} — ${a.ruleId}`);
    lines.push(`- Objects changed: ${c.objectDiffs.length}`);
  }
  lines.push('', '---', 'Generated by God\'s Eye View — ontology brief (client-side data only).');
  return lines.join('\n');
}

/**
 * The closed loop, one call: evaluate rules over the store, compose the
 * brief, render the artifact. `evaluateRules` is injected so the brief never
 * hard-depends on the rule set a surface chose.
 */
export function buildBrief({ store, evaluate, rules, scenario = null, title, now } = {}) {
  const alerts = evaluate(store, rules);
  const brief = composeBrief({ store, alerts, scenario, title, now });
  return { brief, markdown: renderBriefMarkdown(brief), alerts };
}
